<?php

namespace App\Models;

class Movie
{
    static $movie_list = [
        ["id"=>0,"title"=>"Fast X","description"=>"Dom Toretto dan keluarganya menjadi sasaran putra gembong narkoba Hernan Reyes yang pendendam.","release_date"=>"2023-05-17","poster_url"=>"https://image.tmdb.org/t/p/w500/fiVW06jE7z9YnO4trhaMEdclSiC.jpg","age_rating"=>15,"ticket_price"=>53000],
        ["id"=>1,"title"=>"John Wick: Chapter 4","description"=>"ohn Wick mengungkap jalan untuk mengalahkan The High Table. Tapi sebelum dia bisa mendapatkan kebebasannya, Wick harus berhadapan dengan musuh baru dengan aliansi kuat di seluruh dunia dan kekuatan yang mengubah teman lama menjadi musuh.","release_date"=>"2023-03-22","poster_url"=>"https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg","age_rating"=>10,"ticket_price"=>60000],
        ["id"=>2,"title"=>"The Super Mario Bros. Movie","description"=>"Ketika sedang bekerja di bawah tanah untuk memperbaiki pipa air, Mario dan Luigi, yang merupakan tukang ledeng dari Brooklyn, tiba-tiba terhisap ke dalam pipa misterius dan masuk ke dunia yang sangat berbeda. Mereka berada di tempat yang ajaib dan aneh. Tapi sayangnya, mereka terpisah satu sama lain. Mario memulai petualangan besar untuk mencari dan menemukan Luigi.","release_date"=>"2023-04-05","poster_url"=>"https://image.tmdb.org/t/p/w500/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg","age_rating"=>14,"ticket_price"=>49000],
        ["id"=>7,"title"=>"Avatar: The Way of Water","description"=>"Jake Sully tinggal bersama keluarga barunya di planet Pandora. Setelah ancaman kembali datang, Jake harus bekerja dengan Neytiri dan pasukan ras Na'vi untuk melindungi planet mereka.","release_date"=>"2022-12-14","poster_url"=>"https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg","age_rating"=>12,"ticket_price"=>53000],
        ["id"=>9,"title"=>"Guardians of the Galaxy Vol. 3","description"=>"Peter Quill masih trauma karena kehilangan Gamora. Ia perlu mengumpulkan timnya untuk melindungi alam semesta dan salah satu anggota mereka. Jika mereka gagal, Guardian akan berakhir.","release_date"=>"2023-05-03","poster_url"=>"https://image.tmdb.org/t/p/w500/nAbpLidFdbbi3efFQKMPQJkaZ1r.jpg","age_rating"=>12,"ticket_price"=>41000],
        ["id"=>12,"title"=>"Ant-Man and the Wasp: Quantumania","description"=>"Scott Lang dan Hope van Dyne adalah pasangan pahlawan super. Mereka pergi bersama orang tua Hope, Janet van Dyne dan Hank Pym, serta anak perempuan Scott, Cassie Lang, untuk menjelajahi Alam Kuantum. Di sana, mereka bertemu dengan makhluk-makhluk aneh dan memulai petualangan yang tak terduga. Petualangan ini akan menguji batas-batas mereka.","release_date"=>"2023-02-15","poster_url"=>"https://image.tmdb.org/t/p/w500/g0OWGM7HoIt866Lu7yKohYO31NU.jpg","age_rating"=>12,"ticket_price"=>51000],
        ["id"=>17,"title"=>"The Pope's Exorcist","description"=>"Pastor Gabriele Amorth, yang memimpin tim pengusir setan di Vatikan, menginvestigasi kasus kekerasan roh jahat yang menghantui seorang anak laki-laki. Dalam penyelidikannya, ia secara tak terduga menemukan rahasia tua yang disembunyikan oleh Vatikan selama berabad-abad.","release_date"=>"2023-04-05","poster_url"=>"https://image.tmdb.org/t/p/w500/gNPqcv1tAifbN7PRNgqpzY8sEJZ.jpg","age_rating"=>13,"ticket_price"=>51000],
        ["id"=>19,"title"=>"To Catch a Killer","description"=>"Baltimore. Malam tahun baru. Seorang petugas polisi yang berbakat tetapi bermasalah (Shailene Woodley) direkrut oleh kepala penyelidik FBI (Ben Mendelsohn) untuk membantu membuat profil dan melacak individu yang terganggu yang meneror kota.","release_date"=>"2023-04-06","poster_url"=>"https://image.tmdb.org/t/p/w500/mFp3l4lZg1NSEsyxKrdi0rNK8r1.jpg","age_rating"=>15,"ticket_price"=>47000],
        ["id"=>4,"title"=>"Transformers: Age of Extinction","description"=>"Lima tahun setelah Chicago dihancurkan, manusia berbalik melawan robot. Namun seorang ayah tunggal dan penemu membangkitkan robot yang dapat menyelamatkan dunia.","release_date"=>"2014-06-25","poster_url"=>"https://image.tmdb.org/t/p/w500/jyzrfx2WaeY60kYZpPYepSjGz4S.jpg","age_rating"=>11,"ticket_price"=>54000],
        ["id"=>14,"title"=>"Black Adam","description"=>"Hampir 5.000 tahun setelah dia dianugerahi kekuatan maha kuasa para dewa Mesirâ€”dan dipenjara dengan cepatâ€”Black Adam dibebaskan dari makam duniawinya, siap untuk melepaskan bentuk keadilannya yang unik di dunia modern.","release_date"=>"2022-10-19","poster_url"=>"https://image.tmdb.org/t/p/w500/A5imhXiFF3AL9RRA4FBzNDFmfgW.jpg","age_rating"=>10,"ticket_price"=>42000],
        ["id"=>15,"title"=>"Dungeons & Dragons: Honor Among Thieves","description"=>"Seorang pencuri menawan dan sekelompok petualang yang unik melakukan pencurian besar-besaran untuk mencuri relik yang hilang. Namun, segalanya menjadi kacau ketika mereka berjumpa dengan orang yang salah.","release_date"=>"2023-03-23","poster_url"=>"https://image.tmdb.org/t/p/w500/A7AoNT06aRAc4SV89Dwxj3EYAgC.jpg","age_rating"=>12,"ticket_price"=>38000],
        ["id"=>8,"title"=>"Avengers: Infinity War","description"=>"Karena Avengers dan sekutunya terus melindungi dunia dari ancaman yang terlalu besar untuk ditangani oleh seorang pahlawan, bahaya baru telah muncul dari bayangan kosmik: Thanos. Seorang lalim penghujatan intergalaksi, tujuannya adalah untuk mengumpulkan semua enam Batu Infinity, artefak kekuatan yang tak terbayangkan, dan menggunakannya untuk menimbulkan kehendak memutar pada semua realitas. Segala sesuatu yang telah diperjuangkan oleh Avengers telah berkembang hingga saat ini - nasib Bumi dan keberadaannya sendiri tidak pernah lebih pasti.","release_date"=>"2018-04-25","poster_url"=>"https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg","age_rating"=>10,"ticket_price"=>46000],
        ["id"=>13,"title"=>"The Whale","description"=>"Seorang guru bahasa Inggris yang tertutup dan gemuk mencoba untuk berhubungan kembali dengan putri remajanya yang terasing.","release_date"=>"2022-12-09","poster_url"=>"https://image.tmdb.org/t/p/w500/jQ0gylJMxWSL490sy0RrPj1Lj7e.jpg","age_rating"=>15,"ticket_price"=>55000],["id"=>99,"title"=>"The Batman","description"=>"Ketika seorang pembunuh berantai sadis mulai membunuh tokoh-tokoh politik penting di Gotham, Batman terpaksa menyelidiki korupsi tersembunyi di kota itu dan mempertanyakan keterlibatan keluarganya.","release_date"=>"2022-03-01","poster_url"=>"https://image.tmdb.org/t/p/w500/seyWFgGInaLqW7nOZvu0ZC95rtx.jpg","age_rating"=>13,"ticket_price"=>53000],["id"=>98,"title"=>"Smile","description"=>"Setelah menyaksikan kejadian aneh dan traumatis yang melibatkan seorang pasien, Dr. Rose Cotter mulai mengalami kejadian menakutkan yang tidak dapat dia jelaskan. Saat teror luar biasa mulai mengambil alih hidupnya, Rose harus menghadapi masa lalunya yang bermasalah untuk bertahan hidup dan melarikan diri dari kenyataan barunya yang mengerikan.","release_date"=>"2022-09-23","poster_url"=>"https://image.tmdb.org/t/p/w500/67Myda9zANAnlS54rRjQF4dHNNG.jpg","age_rating"=>11,"ticket_price"=>38000],["id"=>97,"title"=>"Encanto","description"=>"menceritakan tentang keluarga Madrigals, sebuah keluarga yang tinggal di rumah ajaib dan masing-masing anggota keluarga memiliki keajaibannya tersendiri. Pada jaman dahulu kala, Abuela bersama suami dan anak-anaknya melarikan diri dari kerusuhan di desa.","release_date"=>"2021-10-13","poster_url"=>"https://image.tmdb.org/t/p/w500/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg","age_rating"=>12,"ticket_price"=>44000]
    ];

    public static function all(){
        return self::$movie_list;
    }

    public static function find($id){
        $movie_list = self::$movie_list;
        $movie = [];
        foreach($movie_list as $m){
            if($m['id']==$id) $movie = $m;
        }
        return $movie;
    }
}
